@url_dev=http://localhost:3052/v1/api/

### signup

POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: df34bb52bbf8e41abf7e40b74fb2cb4a4dbcef732784294f4a1b29bea1067e995fcda13be56637bfccbe34f373a23f9792eea7183e43724cb3d8e572c8f731b0

{
  "name": "Khoa Shop",
  "email": "khoa02@gmail.com",
  "password": "abc123"
}